# Generated by Django 4.0.5 on 2022-09-09 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='компания поставщика')),
                ('number', models.CharField(max_length=30, verbose_name='номер поставщика')),
                ('mail', models.EmailField(max_length=254)),
                ('face', models.CharField(max_length=255, verbose_name='ответсвенное лицо')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщик',
            },
        ),
        migrations.CreateModel(
            name='CompanyOrdeers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqe_key', models.CharField(max_length=255, verbose_name='уникальный ключ')),
                ('name_product', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('sumt', models.IntegerField(max_length=255, verbose_name='количество')),
                ('units', models.CharField(max_length=255, verbose_name='единицы измерения')),
                ('status', models.CharField(max_length=255, verbose_name='статус заказа')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyordeers', to='orders.provider')),
            ],
            options={
                'verbose_name': 'Заказы для компании',
                'verbose_name_plural': 'Заказы для компании',
            },
        ),
    ]
