# Generated by Django 4.0.5 on 2022-09-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyordeers',
            name='sumt',
            field=models.IntegerField(verbose_name='количество'),
        ),
    ]
