# Generated by Django 4.0.5 on 2022-09-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_provider_options_alter_companyordeers_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyordeers',
            name='name_product',
            field=models.CharField(max_length=255, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='companyordeers',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='статус заказа'),
        ),
    ]
