# Generated by Django 4.0.5 on 2022-09-09 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(max_length=255, verbose_name='назначение товара')),
            ],
            options={
                'verbose_name': 'назначение товара',
                'verbose_name_plural': 'назначение товара',
            },
        ),
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(max_length=255, verbose_name='назначение бренда')),
                ('face', models.CharField(max_length=30, verbose_name='Отвечающее лицо')),
                ('contact', models.CharField(max_length=30, verbose_name='номер')),
                ('email', models.EmailField(max_length=254)),
                ('dogovor', models.CharField(max_length=255, verbose_name='Договор действителен до')),
                ('status', models.CharField(max_length=255, verbose_name='статус сотруднечиства')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoinment', models.CharField(max_length=255, verbose_name='категории')),
            ],
        ),
        migrations.CreateModel(
            name='Views_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=255, verbose_name='виды товара')),
            ],
        ),
        migrations.CreateModel(
            name='Util',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование продукта')),
                ('sumt', models.IntegerField(verbose_name='количество товаров')),
                ('date', models.CharField(max_length=255, verbose_name='Дата списания')),
                ('prichina', models.CharField(max_length=255, verbose_name='причина списания товара')),
                ('scode', models.CharField(max_length=60, verbose_name='штрих код')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.appointment_product')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='util', to='product.views_product')),
            ],
            options={
                'verbose_name': 'списанный товар',
                'verbose_name_plural': 'списанный товар',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование продукта')),
                ('sumt', models.IntegerField(verbose_name='количество товаров')),
                ('scode', models.CharField(max_length=60, verbose_name='штрих код')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.appointment_product')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.views_product')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30, verbose_name='Цена')),
                ('units', models.CharField(max_length=255, verbose_name='Единицы измерения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Haracteristic_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sostav', models.CharField(max_length=255, verbose_name='состав')),
                ('color', models.CharField(max_length=255, verbose_name='цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haracteristic_product', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Akcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acketp', models.CharField(max_length=255, verbose_name='Акцепт товаров')),
                ('name', models.CharField(max_length=255, verbose_name='наименование продукта')),
                ('sumt', models.IntegerField(verbose_name='количество товаров')),
                ('daete', models.CharField(max_length=255, verbose_name='Дата продажи')),
                ('scode', models.CharField(max_length=60, verbose_name='штрих код')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.appointment_product')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akcept', to='product.views_product')),
            ],
            options={
                'verbose_name': 'проданный товар',
                'verbose_name_plural': 'проданный товар',
            },
        ),
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование продукта')),
                ('sumt', models.IntegerField(verbose_name='количество товаров')),
                ('scode', models.CharField(max_length=60, verbose_name='штрих код')),
                ('date', models.CharField(max_length=255, verbose_name='дата приема')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.appointment_product')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brend')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept', to='product.views_product')),
            ],
            options={
                'verbose_name': 'Принятый товар',
                'verbose_name_plural': 'Принятый товар',
            },
        ),
    ]
