# Generated by Django 4.0.5 on 2022-09-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='views_product',
            options={'verbose_name': 'Вид товара', 'verbose_name_plural': 'Вид товара'},
        ),
        migrations.AlterField(
            model_name='accept',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.appointment_product', verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='accept',
            name='brend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brend', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='accept',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='akcept',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.appointment_product', verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='akcept',
            name='brend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brend', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='akcept',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='akcept',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akcept', to='product.views_product', verbose_name='Вид товара'),
        ),
        migrations.AlterField(
            model_name='util',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.appointment_product', verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='util',
            name='brend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brend', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='util',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='util',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='util', to='product.views_product', verbose_name='Вид товара'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование продукта')),
                ('sumt', models.IntegerField(verbose_name='количество товаров')),
                ('scode', models.CharField(max_length=60, verbose_name='штрих код')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.appointment_product', verbose_name='Назначение')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brend', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.views_product', verbose_name='вид товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.AlterField(
            model_name='haracteristic_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haracteristic_product', to='product.products'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='product.products', verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
