# Generated by Django 4.0.5 on 2022-09-10 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_views_product_options_alter_accept_appointment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='haracteristic_product',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристика товара'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цена'},
        ),
        migrations.AlterField(
            model_name='accept',
            name='date',
            field=models.DateField(max_length=255, verbose_name='дата приема'),
        ),
        migrations.AlterField(
            model_name='accept',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept', to='product.views_product', verbose_name='Вид товара'),
        ),
        migrations.AlterField(
            model_name='haracteristic_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haracteristic_product', to='product.products', verbose_name='Товар'),
        ),
    ]
