# Generated by Django 4.0.5 on 2022-09-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='appointment',
            field=models.CharField(max_length=255, verbose_name='название бренда'),
        ),
    ]
