# Generated by Django 4.0.5 on 2022-09-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_photo'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='urna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='product.products', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.register', verbose_name='Пользователь')),
            ],
        ),
    ]
