# Generated by Django 4.0.5 on 2022-09-17 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_urna'),
    ]

    operations = [
        migrations.AddField(
            model_name='urna',
            name='summ',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='urna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
