# Generated by Django 4.0.5 on 2022-09-09 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='отчество')),
                ('date_of_birth', models.DateField(verbose_name='дата рождения')),
                ('email', models.EmailField(max_length=254)),
                ('namber_of_phone', models.CharField(max_length=30, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'сотрудники',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Passport_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('no_passport', models.CharField(max_length=255, verbose_name='Номер паспорта')),
                ('location', models.CharField(max_length=255, verbose_name='место выдачи')),
                ('series', models.CharField(max_length=255, verbose_name='Серия паспорта')),
                ('date_start', models.CharField(max_length=255, verbose_name='Дата получения')),
                ('date_end', models.CharField(max_length=255, verbose_name='Дата окончания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passtort_data', to='employees.employee')),
            ],
            options={
                'verbose_name': 'паспортные данные',
                'verbose_name_plural': 'паспортные данные',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(max_length=255, verbose_name='должность')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='DriverLicensie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='категория ВУ')),
                ('expirience', models.CharField(max_length=30, verbose_name='Стаж')),
                ('blood', models.CharField(max_length=30, verbose_name='Группа крови')),
                ('date_start_dl', models.CharField(max_length=30, verbose_name='Дата выдачи ВУ')),
                ('date_end_dl', models.CharField(max_length=30, verbose_name='Дата окончания ВУ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverlicensie', to='employees.employee')),
            ],
            options={
                'verbose_name': 'водительское удостоверение',
                'verbose_name_plural': 'водительское удостоверение',
            },
        ),
    ]
