# Generated by Django 4.0.5 on 2022-09-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicensie',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driverlicensie', to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement', to='employees.employee', verbose_name='Сотрудник'),
        ),
    ]
