# Generated by Django 4.1.1 on 2022-09-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_driverlicensie_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport_data',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passtort_data', to='employees.employee', verbose_name='Сотрудник'),
        ),
    ]
